version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 103119
      POSTGRES_DB: oceans_db
     
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: 103119
      DB_NAME: oceans_db
      DB_PORT: 5432
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"

volumes:
  postgres-data:
